### PR TITLE
Add small features

### PR DESCRIPTION
**Pull request by magic7s**
I added a few small features and thought I should share them back upstream.
* Add UI enabled variable - off by default.
* Add force_destroy option - off by default. Makes testing easy, the bucket gets destroyed automatically. 
~~* Increase container concurrency to 50. This was the number of connects per container that Cloud Run will use. Because there is a small delay to unseal Vault, when spinning up a new container you get errors. Increasing this to 50 allows for many more connections before we hit this "cold start".~~
* Add resource limits based on Cloud Run UI. For some reason the "default" in terraform is a "custom" configuration for Cloud Run.

### CODE REVIEW

**Comment by mbrancato** [comment]
I want to test some things on HA storage before merging this. I've never done Vault HA without Consul, are there any storage lock contention issues, etc?

**Comment by mbrancato** [comment]
I've dug into this. The TLDR is this won't enable HA and I think you want to enable a limit on container copies (not sure this existed when I first wrote this) but allow concurrent requests.

With multiple containers accessing storage, I'm pretty sure you'll hit lock contention problems. To solve this we would need to enable HA in Vault (GCS supports this). The problem is that requires setting the API address and maybe a couple other items. some more work would be needed to enable the API address as a deterministic value. This may be possible with the managed domains and mapping of a domain back to the vault service.

Let me know if you think I'm incorrect here. To achieve the scaling / concurrency, it looks like there are `autoscaling.knative.dev/minScale` and `autoscaling.knative.dev/maxScale` values that can be set. Do you want to update your branch to support this by setting to `1`?

**Comment by magic7s** [comment]
When I was reading up on [concurrency](https://cloud.google.com/run/docs/about-concurrency) the docs imply that a concurrency of 1 would spin a new container for every new request. I was seeing “vault is sealed” errors because of the small delay of a new container needing time to unseal before handling a request. Changing to 50 (no logic behind this number) allows a single container to handle 50 requests before scaling. My use case usage is so low I didn’t test any storage contention. But what you described sounds like the opposite of what you want.

**Comment by magic7s** [comment]
I was not trying to setup HA as my use case does not need it, however I feel like the architecture is fairly redundant as is. CloudRun/K8s tracks health and spins new containers as needed, storage is redundant by default, and unseal keys are in a “service”. That’s good enough for me.

**Comment by mbrancato** [comment]
Agreed and that’s why I didn’t target HA initially. If you keep the PR as is but add the maxScale annotation I think it would be fine to merge and wouldn’t cause any storage issues.

**Comment by magic7s** [comment]
I think I get it now. It might be wise to pull out the concurrence and scale into its own PR to not mix with the other items. I’ll pull it out and start a new PR.

**Comment by magic7s** [comment]
@mbrancato ready for review

**Comment by mbrancato** [comment]
good deal - lgtm

**Pull request merged**
